# Generated by Django 6.1 on 2026-08-25 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0003_jobpostmodel_jobapplymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostmodel',
            name='Recruiters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
